Fix protobuff to v. 3.1.0
Newer version of protobuf (e.g. post 3.1.0) require generated files to
have the postifix <file>_p2.py. mapbox-vector-file version 0.5.0 does
not conform to this naming scheme and will throw:

TypeError: Descriptors should not be created directly, but only
retrieved from their parent.

errors under python 3.